steps:
  test:
    when:
      - event: push
        branch: main
      - event: pull_request
        branch: main
    image: codeberg.org/foxy/tree-sitter:0.24.4-r0
    commands:
      - tree-sitter init-config
      # ISO Prolog
      - cd grammars/prolog/
      - tree-sitter generate --no-bindings
      - tree-sitter test && tree-sitter parse examples/*.pl --quiet --time
      # Problog
      - cd ../../grammars/problog/
      - tree-sitter generate --no-bindings
      - tree-sitter test && tree-sitter parse examples/*.pl --quiet --time
      # Syntax highlighting
      - cd ../.. && tree-sitter test
  diff:
    when:
      - event: push
        branch: main
      - event: pull_request
        branch: main
    image: bitnami/git
    commands:
      - |
        if [ "$(git status --porcelain)" ]; then
          git status --porcelain
          exit 1
        fi
